# Generated by Django 2.1.2 on 2018-11-05 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('point_recd', models.IntegerField(default=0)),
                ('point_tosd', models.IntegerField(default=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_price', models.IntegerField(default=100)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='transaction date stamp')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Message')),
                ('rdm_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Redemption')),
                ('rec_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='webapp.Employee')),
                ('send_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='webapp.Employee')),
            ],
        ),
    ]
